# Generated by Django 6.0.4 on 2026-05-01 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sport', 'Sport'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('mpv', 'MPV')], default='suv', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('fuel_capacity', models.IntegerField(default=50)),
                ('seats', models.IntegerField(default=4)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('bitcoin', 'Bitcoin')], max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
