# Generated by Django 6.0.4 on 2026-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_description_car_rating_alter_car_fuel_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='car',
            name='reviews',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(default=280),
        ),
    ]
